# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        /:year/:month/:day/:title/

# Custom vars
version:          2.1.0

github:           metadata

repository:       pepellou/pepellou.github.io
userdisqus:       pepellou

# Setup
author:
  name:           "Pepe Doval"
  url:            https://twitter.com/pepellou
  twitter:        pepellou

paginate:         5

title:            "Be Chess"
tagline:          "You all be chess"
description:      "First step to enlightenment is not to seek for enlightenment."
locale:           es_es
encoding:         utf-8
url:              https://pepellou.github.io
baseurl:          https://pepellou.github.io/  
google_analytics: UA-XXXXXXXXX-X
