# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        /:year/:month/:day/:title/

# Custom vars
version:          2.1.0

github:           metadata

repository:       pepellou/chess-is-hard
userdisqus:       pepellou

# Setup
author:
  name:           "Pepe Doval"
  url:            https://twitter.com/pepellou
  twitter:        pepellou

paginate:         5

title:            "Chess is Hard"
tagline:          "First step to enlightenment is not to seek for enlightenment."
description:      "Lights and shadows of a chess learning experience"
locale:           es_es
encoding:         utf-8
url:              https://pepellou.github.io/chess-is-hard
baseurl:          https://pepellou.github.io/chess-is-hard/ 
google_analytics: UA-XXXXXXXXX-X
